INSERT INTO course (id, name, description)
VALUES (gen_random_uuid(), 'Introduction to Computer Science',
        'This course provides an overview of computer science, including algorithms, data structures, software development, and computer systems.'),
       (gen_random_uuid(), 'Data Structures and Algorithms',
        'This course covers fundamental data structures and algorithms, including arrays, linked lists, stacks, queues, trees, graphs, sorting, and searching.'),
       (gen_random_uuid(), 'Database Systems',
        'This course introduces database design, SQL, and database management systems. Topics include relational databases, normalization, and transactions.'),
       (gen_random_uuid(), 'Operating Systems',
        'This course explores the principles of operating systems, including process management, memory management, file systems, and concurrency.'),
       (gen_random_uuid(), 'Computer Networks',
        'This course covers the fundamentals of computer networking, including network protocols, architecture, security, and wireless communication.'),
       (gen_random_uuid(), 'Software Engineering',
        'This course focuses on software development methodologies, project management, software design patterns, and quality assurance.'),
       (gen_random_uuid(), 'Web Development',
        'This course teaches the basics of web development, including HTML, CSS, JavaScript, and web frameworks for building dynamic web applications.'),
       (gen_random_uuid(), 'Cybersecurity',
        'This course provides an introduction to cybersecurity principles, including threat analysis, cryptography, network security, and risk management.'),
       (gen_random_uuid(), 'Artificial Intelligence',
        'This course covers the basics of artificial intelligence, including machine learning, neural networks, natural language processing, and robotics.'),
       (gen_random_uuid(), 'Cloud Computing',
        'This course introduces cloud computing concepts, including cloud architecture, services, deployment models, and cloud security.'),
       (gen_random_uuid(), 'Mobile Application Development',
        'This course covers the development of mobile applications, including design principles, user interfaces, and platform-specific considerations.'),
       (gen_random_uuid(), 'Human-Computer Interaction',
        'This course explores the design and evaluation of user interfaces, focusing on usability, user experience, and interaction design.'),
       (gen_random_uuid(), 'Big Data Analytics',
        'This course introduces big data technologies and techniques, including data mining, data warehousing, and data visualization.'),
       (gen_random_uuid(), 'Machine Learning',
        'This course covers machine learning algorithms and techniques, including supervised and unsupervised learning, and model evaluation.'),
       (gen_random_uuid(), 'Computer Graphics',
        'This course explores the principles of computer graphics, including rendering, modeling, animation, and visualization techniques.'),
       (gen_random_uuid(), 'Distributed Systems',
        'This course covers the design and implementation of distributed systems, including communication, synchronization, and fault tolerance.'),
       (gen_random_uuid(), 'Network Security',
        'This course focuses on network security principles, including encryption, firewalls, intrusion detection, and secure communication protocols.'),
       (gen_random_uuid(), 'Software Testing and Quality Assurance',
        'This course covers software testing methodologies, test automation, and quality assurance practices to ensure software reliability and performance.'),
       (gen_random_uuid(), 'Embedded Systems',
        'This course introduces embedded systems design, including hardware-software integration, real-time operating systems, and microcontroller programming.'),
       (gen_random_uuid(), 'Blockchain Technology',
        'This course explores blockchain technology, including its architecture, consensus mechanisms, smart contracts, and applications in various industries.');